"""empty message

Revision ID: 13897f8cddf6
Revises: 4e56c9026e58
Create Date: 2019-10-09 23:24:43.720046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13897f8cddf6'
down_revision = '4e56c9026e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('composition', sa.String(length=100), nullable=True))
    op.add_column('sample', sa.Column('experiments', sa.PickleType(), nullable=True))
    op.add_column('sample', sa.Column('fab_date', sa.Date(), nullable=True))
    op.add_column('sample', sa.Column('fab_method', sa.String(length=100), nullable=True))
    op.add_column('sample', sa.Column('notes', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_sample_composition'), 'sample', ['composition'], unique=False)
    op.create_index(op.f('ix_sample_experiments'), 'sample', ['experiments'], unique=False)
    op.create_index(op.f('ix_sample_fab_date'), 'sample', ['fab_date'], unique=False)
    op.create_index(op.f('ix_sample_fab_method'), 'sample', ['fab_method'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sample_fab_method'), table_name='sample')
    op.drop_index(op.f('ix_sample_fab_date'), table_name='sample')
    op.drop_index(op.f('ix_sample_experiments'), table_name='sample')
    op.drop_index(op.f('ix_sample_composition'), table_name='sample')
    op.drop_column('sample', 'notes')
    op.drop_column('sample', 'fab_method')
    op.drop_column('sample', 'fab_date')
    op.drop_column('sample', 'experiments')
    op.drop_column('sample', 'composition')
    # ### end Alembic commands ###
